baseURL = 'https://toddemerson.com/'
languageCode = 'en-us'
title = 'Todd Emerson'
theme = 'hugo-coder'


[params]
  text_color = ""
  author = "A. Todd Emerson"
  info = ["Results-Driven Product & Business Development"]
  favicon = ""
  site_logo = ""
  description = "Todd Emerson's personal website"
  keywords = "blog, personal"
  avatarURL = "images/ToddEmerson_avatar.jpg"
  faviconSVG = "images/favicon.svg"
  favicon_32 = "images/favicon_32.png"
  favicon_16 = "images/favicon_16.png"
  touchIcon = ""
  mask_icon = ""
  mask_icon_color = "#5bbad5"
  since = ""
  maxSeeAlsoItems = ""
  colorScheme = "auto"
  hideColorSchemeToggle = "false"
  enableTwemoji = "false"
  disableDefaultJsScripts = "false"
  poweredby = ""
  customSCSS = ["scss/custom.scss"]
  # cusdis = "https://cusdis.com"

[markup.goldmark]
[markup.goldmark.renderer]
unsafe = true

# information found in config.toml   
[taxonomies]
  category = "categories"
  series = "series"
  tag = "tags"
  author = "authors"

# Menus
[[menu.main]]
 name = "About"
 weight = 1
 url = "about/"

[[menu.main]]
#  name = "Contact"
#  weight = 2
#  url = "contact/"

[[menu.main]]
  name = "Blog: The Outsider"
  weight = 3
  url = "posts/"

[[menu.main]]
name = "My Dad: Warren Emerson"
weight = 3
url = "wemerson/"

# Social links
[[params.social]]
  name = "LinkedIn"
  icon = "fa-brands fa-linkedin fa-2x"
  weight = 1
  url = "https://www.linkedin.com/in/toddemerson/"

[[params.social]]
  name = "Github"
  icon = "fa-brands fa-github fa-2x"
  weight = 1
  url = "https://github.com/ToddE"

# [params.cusdis] # https://cusdis.com
#   data_app_id = "dd95f208-2371-4bc7-83df-a3b2b31834d4"

[params.giscus] # https://giscus.app
  repo = "ToddE/website-toddemerson.com"
  repoID = "R_kgDOL53jKw"
  category = "General"
  categoryID = "DIC_kwDOL53jK84Cpa1u"
  mapping = "pathname"
  term = ""
  strict = "0"
  reactionsEnabled = "1"
  emitMetadata = "0"
  inputPosition = "bottom"
  theme = "preferred_color_scheme"
  lang = "en"
  loading = ""

[params.umami]
    siteID = "2bd6d18d-3fb9-4fbd-a934-d2e4ab7755e6"
    scriptURL = "https://cloud.umami.is/script.js" 
    # refer to the "tracking code" tab in your umami website dashboard 
    # to obtain the script url

[deployment]

[[deployment.targets]]
# An arbitrary name for this target.
name = "production"

# # URL specifies the Go Cloud Development Kit URL to deploy to. Examples:
# URL = "s3://website-toddemerson.com?region=us-east-1"