# These lines should *not* be indented


backend:
  name: github
  repo: ToddE/website-toddemerson.com
  branch: master # Branch to update (optional; defaults to master)
  use_graphql: true
media_folder: "static/images" # Media files will be stored in the repo under static/images/uploads
public_folder: "/images" # The src attribute for uploaded media will begin with /images/uploads
collections:
  - label: "Pages"
    name: "pages"
    editor:
      preview: true
    files:
      - label: 'About'
        name: 'about'
        file: '/content/about.md'
        fields:
          - { label: Content, name: content, widget: markdown }
      - label: "Contact"
        name: 'contact'
        file: 'content/contact.md'
        fields:
          - { label: 'Content', name: 'content', widget: 'markdown' }
  - label: 'Blog'
    name: 'blog'
    folder: 'content/blog'
    create: true
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    editor:
      preview: true
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Publish Date', name: 'date', widget: 'datetime' }
      - { label: 'Description', name: 'description', widget: 'string' }
      - { label: 'Author', name: "author", widget: 'string' }
      - { label: 'Body', name: 'body', widget: 'markdown' }
